name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build JAR file
        run: |
          mvn clean package -DskipTests
          ls -lh target/

      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}